# Generated by Django 2.1.2 on 2018-10-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
